# build rules and dependencies

EXTRA_INC = $(CGMAP_INC) $(TCL_INC) 
EXTRA_PATH = $(TCL_PATH)
EXTRA_LIB =  $(TCL_LIB) $(TCL_STUB_LIB)

shlib:  $(OBJ)
	$(CC) $(CCFLAGS) $(SHFLAGS) $(SHLIBFLAGS) $(EXTRA_PATH) -o $(EXE) \
	$(OBJ) $(EXTRA_LIB) $(LIB)

# Compilation rules
%.o:%.cpp
	$(CC) $(CCFLAGS) $(SHFLAGS) $(EXTRA_INC) -c $<
